genericviews/genericviews/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('genericviewsapp.urls'))
]

genericviews/genericviewsapp/urls.py
from django.urls import path, include
from .views import * 
urlpatterns = [
    path('list/', PublisherListView.as_view()),
    path('<pk>', PublisherDetailView.as_view()),
]

genericviews/genericviewsapp/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    city = models.CharField(max_length=60)

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

genericviews/genericviewsapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from .models import *

class PublisherListView(ListView):
    model = Publisher
    template_name = "index.html"
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['book_list'] = Book.objects.all()
        context['author_list'] = Author.objects.all()
        print("CONTEXT", context)
        return context

class PublisherDetailView(DetailView):
    template_name = "index.html"
    queryset = Book.objects.all()
    context_object_name = 'book_list'

genericviews/genericviewsapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generic View</title>
    <style>
        body {
            width: 100%;
        }
        ul {
            justify-content: space-between;
            text-align: center;
            width: 50%;
            display: flex;
            gap: 2rem;
        }
         li { 
            list-style-type: none;
            font-size: 2rem;
         }
    </style>
</head>
<body>
    <h2>Publishers</h2>
    <h1>{{ object.title }}</h1>

    <!-- 
    {% for publisher in publisher_list %}

    <ul>
            <li>{{ publisher.name }}</li>
            <li>{{ publisher.city }}</li>
        
    </ul>
    {% endfor %}
    {% for author in author_list %}

    <ul>
            <li>{{ author.name }}</li>
            <li>{{ author.email }}</li>
        
    </ul>
    {% endfor %} -->
</body>
</html>